What is a Abstraction?

In [ ]:
i = [1,2,3]
print(sum(i))

6


No 1 + 2 + 3 explicitly.
Pytorch abstracts Neural network stages.

https://pytorch.org/get-started/locally/

In [ ]:
!pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126


In [ ]:
import torch

In [ ]:
data = [[1]]
x = torch.tensor(data)
# (consists of shape, datatype, device)

In [ ]:
print(x)

tensor([[1]])


In [ ]:
print(f"Shape: {x.shape}")
print(f"Datatype: {x.dtype}")
print(f"Device: {x.device}")

Shape: torch.Size([1, 1])
Datatype: torch.int64
Device: cpu


How to specify shapes?

In [ ]:
torch.rand(4)

tensor([0.5926, 0.5129, 0.3170, 0.5632])

In [ ]:
torch.rand(2, 3)

tensor([[0.3466, 0.3946, 0.1790],
        [0.9502, 0.4292, 0.9533]])

Array

In [ ]:
# Create a tensor starting at 0, ending at 1.0 (inclusive), with a step of 0.1
# range_0_1 = torch.arange(0, 1.0, 0.1)
range_0_1 = torch.arange(0, 1.0 + 0.0001, 0.1)
# Note: Adding a small epsilon (e.g., 0.0001) to the stop value is a common practice
# with floating-point steps to ensure the final value (1.0) is included due to
# potential floating-point arithmetic inaccuracies.

print(range_0_1)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [ ]:
range_0_1 = torch.arange(0, 1.1, 0.1)
range_0_1

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

In [ ]:
# We know how to index in python list
i = [0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,0.9000, 1.0000]
print(i[5])

0.5


In [ ]:
# Define the possible values as a PyTorch tensor
possible_values = torch.arange(0.0, 1.1, 0.1)

# Generate a single random integer index from 0 up to (but not including) the size of the tensor
random_index = torch.randint(low=0, high=possible_values.size(0), size=(1,1))

# # Select the value at the random index and extract the float number
# random_float = possible_values[random_index]
random_float = possible_values[random_index].item()

# Print the result
print(random_float)

# # Use f-string formatting to print with 1 decimal place
# print(f"{random_float:.1f}")

0.30000001192092896


$\frac{\partial L}{\partial w}$ &nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp; loss.backward()

$\frac{\partial L}{\partial w}$ &nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp; W.grad

W = W - (learning_rate * W.grad) &nbsp;&nbsp;&nbsp; :&nbsp;&nbsp;&nbsp; optimizer.step()

In [ ]:
# --- 1. Define Data and Hyperparameters ---
x_data = torch.tensor([[1.0]])
y_true = torch.tensor([[1.0]])
# --- Model Parameter (W) ---
W = torch.tensor([[0.2]], requires_grad=True)
# --- Hyperparameters
learning_rate = 0.1
num_epochs = 200


for epoch in range(num_epochs):

    ### STEP 1: Forward Pass (Calculate Prediction) ###
    y_pred = W @ x_data

    ### STEP 2: Calculate Loss ###
    loss = y_true - y_pred

    ### STEP 3: Backward Pass (Calculate Gradients) ###
    loss.backward()

    ### STEP 4: Update Parameters (The Manual Gradient Descent Step) ###
    with torch.no_grad():
        # W = W - (learning_rate * W.grad)
        W -= (learning_rate * W.grad)

    ### STEP 5: Reset means Zero the Gradients for the next iteration###
    W.grad.zero_()

    # --- Print and Break Condition ---
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.6f}, Current W: {W.item():.4f}")

    # Break condition requested by the user
    if loss.item() < 0.1:
        print(f"\nBreak condition met: Loss ({loss.item():.6f}) < 0.1")
        break

print("---------------------------------------")
print(f"Final optimized weight (W): {W.item():.4f}")
print(f"Target W should be 1.0.")

Epoch [1/200], Loss: 0.800000, Current W: 0.3000
Epoch [2/200], Loss: 0.700000, Current W: 0.4000
Epoch [3/200], Loss: 0.600000, Current W: 0.5000
Epoch [4/200], Loss: 0.500000, Current W: 0.6000
Epoch [5/200], Loss: 0.400000, Current W: 0.7000
Epoch [6/200], Loss: 0.300000, Current W: 0.8000
Epoch [7/200], Loss: 0.200000, Current W: 0.9000
Epoch [8/200], Loss: 0.100000, Current W: 1.0000

Break condition met: Loss (0.100000) < 0.1
---------------------------------------
Final optimized weight (W): 1.0000
Target W should be 1.0.


In [ ]:
# With Comments
# --- 1. Define Data and Hyperparameters ---
x_data = torch.tensor([[1.0]])
y_true = torch.tensor([[1.0]])
learning_rate = 0.1
num_epochs = 200

# --- 2. Initialize Model Parameter (W) ---
# Start W at 0.2
W = torch.tensor([[0.2]], requires_grad=True)

print(f"Starting value of W: {W.item():.4f}")
print("---------------------------------------")

for epoch in range(num_epochs):

    ### STEP 1: Forward Pass (Calculate Prediction) ###
    y_pred = W * x_data

    ### STEP 2: Calculate Loss ###
    # Loss = y_true - y_pred. This loss tries to drive W to infinity.
    loss = y_true - y_pred

    ### STEP 3: Backward Pass (Calculate Gradients) ###
    loss.backward()

    ### STEP 4: Update Parameters (The Manual Gradient Descent Step) ###
    # We wrap this in no_grad() because this is not part of the model's computation
    with torch.no_grad():
        # Update W in-place using W.data.sub_() to maintain the computation graph
        # W = W - (learning_rate * W.grad)
        W.data.sub_(learning_rate * W.grad)

    ### STEP 5: Zero the Gradients ###
    # We must reset the gradients for the next iteration
    W.grad.zero_()

    # --- Print and Break Condition ---
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.6f}, Current W: {W.item():.4f}")
    # if (epoch + 1) % 10 == 0 or loss.item() < 0.1:


    # Break condition requested by the user
    if loss.item() < 0.1:
        print(f"\nBreak condition met: Loss ({loss.item():.6f}) < 0.1")
        break

print("---------------------------------------")
print(f"Final optimized weight (W): {W.item():.4f}")
print(f"Target W should be 1.0.")

Starting value of W: 0.2000
---------------------------------------
Epoch [1/200], Loss: 0.800000, Current W: 0.3000
Epoch [2/200], Loss: 0.700000, Current W: 0.4000
Epoch [3/200], Loss: 0.600000, Current W: 0.5000
Epoch [4/200], Loss: 0.500000, Current W: 0.6000
Epoch [5/200], Loss: 0.400000, Current W: 0.7000
Epoch [6/200], Loss: 0.300000, Current W: 0.8000
Epoch [7/200], Loss: 0.200000, Current W: 0.9000
Epoch [8/200], Loss: 0.100000, Current W: 1.0000

Break condition met: Loss (0.100000) < 0.1
---------------------------------------
Final optimized weight (W): 1.0000
Target W should be 1.0.


In [ ]:
# Needed
import torch.optim as optim

# --- 1. Define Data ---
x_data = torch.tensor([[1.0]])
true_W = torch.tensor([[1.0]])
y_true = x_data @ true_W

# --- 2. Initialize Model Parameters ---
W = torch.tensor([[0.2]], requires_grad=True)

y_pred = W @ x_data

# --- 3. Define the Custom Loss Function and Optimizer ---
# Custom Loss: Loss = y - predicted_y (y - w*x)
loss = y_true - y_pred

learning_rate = 0.1
optimizer = optim.SGD([W], lr=learning_rate)

# --- 4. Training Loop ---
num_epochs = 100

print(f"Starting value of w: {W.item():.2f}")

for epoch in range(num_epochs):
    # a. Forward Pass: Calculate the prediction
    y_pred = W @ x_data

    # b. Calculate Loss: Loss = y - w*x
    loss = y_true - y_pred

    # c. Zero Gradients
    optimizer.zero_grad()

    # d. Backward Pass: Calculate the gradient
    loss.backward()

    # e. Update Weights
    optimizer.step()

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.3f}, Current w: {w.item():.2f}")

   7

    # # f. Print progress
    # if (epoch + 1) % 10 == 0:
    #     print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.6f}, Current w: {w.item():.4f}")

# --- 5. Final Result ---
print(f"The final weight (w) is: {W.item():.2f}")

Starting value of w: 0.20
Epoch [1/100], Loss: 0.800, Current w: 1.00
Epoch [2/100], Loss: 0.700, Current w: 1.00
Epoch [3/100], Loss: 0.600, Current w: 1.00
Epoch [4/100], Loss: 0.500, Current w: 1.00
Epoch [5/100], Loss: 0.400, Current w: 1.00
Epoch [6/100], Loss: 0.300, Current w: 1.00
Epoch [7/100], Loss: 0.200, Current w: 1.00
Epoch [8/100], Loss: 0.100, Current w: 1.00
The final weight (w) is: 1.00


In [ ]:
# Using MSE loss
import torch
import torch.nn as nn
import torch.optim as optim

# --- 1. Data Initialization ---
# The target data is x=1, y=1.
# The relationship is y = w * x, so the optimal w should be 1.0.
X = torch.tensor([1.0])
Y = torch.tensor([1.0])

# --- 2. Model Parameter Initialization ---
# Initialize the weight 'w' as a Tensor that requires gradients.
# This makes 'w' a learnable parameter.
w = torch.tensor([0.2], requires_grad=True)

# --- 3. Optimizer and Loss Function ---
# We use Stochastic Gradient Descent (SGD) to update 'w'.
# The learning rate (lr) controls the step size of the update.
learning_rate = 0.05
optimizer = optim.SGD([w], lr=learning_rate)

# We must use a standard loss function like Mean Squared Error (MSE).
# Note: The loss requested by the user (Loss = Y - Y_pred) is unsuitable for
# minimization because minimizing L = 1 - w would drive w to infinity, not 1.
loss_function = nn.MSELoss()

# --- 4. Training Loop ---
num_epochs = 100

print(f"Initial W: {w.item():.4f}")
print("--- Training Started ---")

for epoch in range(num_epochs):
    # Zero the gradients from the previous iteration
    optimizer.zero_grad()

    # 1. Forward Pass: Calculate the prediction
    # Predict Y (Y_pred) using the current W and input X
    Y_pred = w * X

    # 2. Calculate the Loss
    loss = loss_function(Y_pred, Y)

    # 3. Backward Pass: Calculate gradients (dLoss/dW)
    loss.backward()

    # 4. Update Weights: Adjust W using the calculated gradient
    # w = w - lr * (dLoss/dW)
    optimizer.step()

    # Print status every 10 epochs
    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch+1:03}/{num_epochs}] | Loss: {loss.item():.6f} | Current W: {w.item():.4f}")

print("--- Training Finished ---")
print(f"Target Y: {Y.item()}")
print(f"Final W: {w.item():.4f}")
print(f"Final Predicted Y: {(w * X).item():.4f}")


Initial W: 0.2000
--- Training Started ---
Epoch [010/100] | Loss: 0.096061 | Current W: 0.7211
Epoch [020/100] | Loss: 0.011679 | Current W: 0.9027
Epoch [030/100] | Loss: 0.001420 | Current W: 0.9661
Epoch [040/100] | Loss: 0.000173 | Current W: 0.9882
Epoch [050/100] | Loss: 0.000021 | Current W: 0.9959
Epoch [060/100] | Loss: 0.000003 | Current W: 0.9986
Epoch [070/100] | Loss: 0.000000 | Current W: 0.9995
Epoch [080/100] | Loss: 0.000000 | Current W: 0.9998
Epoch [090/100] | Loss: 0.000000 | Current W: 0.9999
Epoch [100/100] | Loss: 0.000000 | Current W: 1.0000
--- Training Finished ---
Target Y: 1.0
Final W: 1.0000
Final Predicted Y: 1.0000
